// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteApiV2AuthSessionsByReferenceNumberData,
  DeleteApiV2AuthSessionsByReferenceNumberErrors,
  DeleteApiV2AuthSessionsByReferenceNumberResponses,
  DeleteApiV2AuthSessionsCurrentData,
  DeleteApiV2AuthSessionsCurrentErrors,
  DeleteApiV2AuthSessionsCurrentResponses,
  DeleteApiV2PermissionsAuthorizationsGrantsByPermissionIdData,
  DeleteApiV2PermissionsAuthorizationsGrantsByPermissionIdErrors,
  DeleteApiV2PermissionsAuthorizationsGrantsByPermissionIdResponses,
  DeleteApiV2PermissionsCommonGrantsByPermissionIdData,
  DeleteApiV2PermissionsCommonGrantsByPermissionIdErrors,
  DeleteApiV2PermissionsCommonGrantsByPermissionIdResponses,
  DeleteApiV2TestdataLimitsContextSessionData,
  DeleteApiV2TestdataLimitsContextSessionErrors,
  DeleteApiV2TestdataLimitsContextSessionResponses,
  DeleteApiV2TestdataLimitsSubjectCertificateData,
  DeleteApiV2TestdataLimitsSubjectCertificateErrors,
  DeleteApiV2TestdataLimitsSubjectCertificateResponses,
  DeleteApiV2TestdataRateLimitsData,
  DeleteApiV2TestdataRateLimitsErrors,
  DeleteApiV2TestdataRateLimitsResponses,
  DeleteApiV2TokensByReferenceNumberData,
  DeleteApiV2TokensByReferenceNumberErrors,
  DeleteApiV2TokensByReferenceNumberResponses,
  GetApiV2AuthByReferenceNumberData,
  GetApiV2AuthByReferenceNumberErrors,
  GetApiV2AuthByReferenceNumberResponses,
  GetApiV2AuthSessionsData,
  GetApiV2AuthSessionsErrors,
  GetApiV2AuthSessionsResponses,
  GetApiV2CertificatesEnrollmentsByReferenceNumberData,
  GetApiV2CertificatesEnrollmentsByReferenceNumberErrors,
  GetApiV2CertificatesEnrollmentsByReferenceNumberResponses,
  GetApiV2CertificatesEnrollmentsDataData,
  GetApiV2CertificatesEnrollmentsDataErrors,
  GetApiV2CertificatesEnrollmentsDataResponses,
  GetApiV2CertificatesLimitsData,
  GetApiV2CertificatesLimitsErrors,
  GetApiV2CertificatesLimitsResponses,
  GetApiV2InvoicesExportsByReferenceNumberData,
  GetApiV2InvoicesExportsByReferenceNumberErrors,
  GetApiV2InvoicesExportsByReferenceNumberResponses,
  GetApiV2InvoicesKsefByKsefNumberData,
  GetApiV2InvoicesKsefByKsefNumberErrors,
  GetApiV2InvoicesKsefByKsefNumberResponses,
  GetApiV2LimitsContextData,
  GetApiV2LimitsContextErrors,
  GetApiV2LimitsContextResponses,
  GetApiV2LimitsSubjectData,
  GetApiV2LimitsSubjectErrors,
  GetApiV2LimitsSubjectResponses,
  GetApiV2PeppolQueryData,
  GetApiV2PeppolQueryErrors,
  GetApiV2PeppolQueryResponses,
  GetApiV2PermissionsAttachmentsStatusData,
  GetApiV2PermissionsAttachmentsStatusErrors,
  GetApiV2PermissionsAttachmentsStatusResponses,
  GetApiV2PermissionsOperationsByReferenceNumberData,
  GetApiV2PermissionsOperationsByReferenceNumberErrors,
  GetApiV2PermissionsOperationsByReferenceNumberResponses,
  GetApiV2PermissionsQueryEntitiesRolesData,
  GetApiV2PermissionsQueryEntitiesRolesErrors,
  GetApiV2PermissionsQueryEntitiesRolesResponses,
  GetApiV2RateLimitsData,
  GetApiV2RateLimitsErrors,
  GetApiV2RateLimitsResponses,
  GetApiV2SecurityPublicKeyCertificatesData,
  GetApiV2SecurityPublicKeyCertificatesErrors,
  GetApiV2SecurityPublicKeyCertificatesResponses,
  GetApiV2SessionsByReferenceNumberData,
  GetApiV2SessionsByReferenceNumberErrors,
  GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberData,
  GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberErrors,
  GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberResponses,
  GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpoData,
  GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpoErrors,
  GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpoResponses,
  GetApiV2SessionsByReferenceNumberInvoicesData,
  GetApiV2SessionsByReferenceNumberInvoicesErrors,
  GetApiV2SessionsByReferenceNumberInvoicesFailedData,
  GetApiV2SessionsByReferenceNumberInvoicesFailedErrors,
  GetApiV2SessionsByReferenceNumberInvoicesFailedResponses,
  GetApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpoData,
  GetApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpoErrors,
  GetApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpoResponses,
  GetApiV2SessionsByReferenceNumberInvoicesResponses,
  GetApiV2SessionsByReferenceNumberResponses,
  GetApiV2SessionsByReferenceNumberUpoByUpoReferenceNumberData,
  GetApiV2SessionsByReferenceNumberUpoByUpoReferenceNumberErrors,
  GetApiV2SessionsByReferenceNumberUpoByUpoReferenceNumberResponses,
  GetApiV2SessionsData,
  GetApiV2SessionsErrors,
  GetApiV2SessionsResponses,
  GetApiV2TokensByReferenceNumberData,
  GetApiV2TokensByReferenceNumberErrors,
  GetApiV2TokensByReferenceNumberResponses,
  GetApiV2TokensData,
  GetApiV2TokensErrors,
  GetApiV2TokensResponses,
  PostApiV2AuthChallengeData,
  PostApiV2AuthChallengeErrors,
  PostApiV2AuthChallengeResponses,
  PostApiV2AuthKsefTokenData,
  PostApiV2AuthKsefTokenErrors,
  PostApiV2AuthKsefTokenResponses,
  PostApiV2AuthTokenRedeemData,
  PostApiV2AuthTokenRedeemErrors,
  PostApiV2AuthTokenRedeemResponses,
  PostApiV2AuthTokenRefreshData,
  PostApiV2AuthTokenRefreshErrors,
  PostApiV2AuthTokenRefreshResponses,
  PostApiV2AuthXadesSignatureData,
  PostApiV2AuthXadesSignatureErrors,
  PostApiV2AuthXadesSignatureResponses,
  PostApiV2CertificatesByCertificateSerialNumberRevokeData,
  PostApiV2CertificatesByCertificateSerialNumberRevokeErrors,
  PostApiV2CertificatesByCertificateSerialNumberRevokeResponses,
  PostApiV2CertificatesEnrollmentsData,
  PostApiV2CertificatesEnrollmentsErrors,
  PostApiV2CertificatesEnrollmentsResponses,
  PostApiV2CertificatesQueryData,
  PostApiV2CertificatesQueryErrors,
  PostApiV2CertificatesQueryResponses,
  PostApiV2CertificatesRetrieveData,
  PostApiV2CertificatesRetrieveErrors,
  PostApiV2CertificatesRetrieveResponses,
  PostApiV2InvoicesExportsData,
  PostApiV2InvoicesExportsErrors,
  PostApiV2InvoicesExportsResponses,
  PostApiV2InvoicesQueryMetadataData,
  PostApiV2InvoicesQueryMetadataErrors,
  PostApiV2InvoicesQueryMetadataResponses,
  PostApiV2PermissionsAuthorizationsGrantsData,
  PostApiV2PermissionsAuthorizationsGrantsErrors,
  PostApiV2PermissionsAuthorizationsGrantsResponses,
  PostApiV2PermissionsEntitiesGrantsData,
  PostApiV2PermissionsEntitiesGrantsErrors,
  PostApiV2PermissionsEntitiesGrantsResponses,
  PostApiV2PermissionsEuEntitiesAdministrationGrantsData,
  PostApiV2PermissionsEuEntitiesAdministrationGrantsErrors,
  PostApiV2PermissionsEuEntitiesAdministrationGrantsResponses,
  PostApiV2PermissionsEuEntitiesGrantsData,
  PostApiV2PermissionsEuEntitiesGrantsErrors,
  PostApiV2PermissionsEuEntitiesGrantsResponses,
  PostApiV2PermissionsIndirectGrantsData,
  PostApiV2PermissionsIndirectGrantsErrors,
  PostApiV2PermissionsIndirectGrantsResponses,
  PostApiV2PermissionsPersonsGrantsData,
  PostApiV2PermissionsPersonsGrantsErrors,
  PostApiV2PermissionsPersonsGrantsResponses,
  PostApiV2PermissionsQueryAuthorizationsGrantsData,
  PostApiV2PermissionsQueryAuthorizationsGrantsErrors,
  PostApiV2PermissionsQueryAuthorizationsGrantsResponses,
  PostApiV2PermissionsQueryEuEntitiesGrantsData,
  PostApiV2PermissionsQueryEuEntitiesGrantsErrors,
  PostApiV2PermissionsQueryEuEntitiesGrantsResponses,
  PostApiV2PermissionsQueryPersonalGrantsData,
  PostApiV2PermissionsQueryPersonalGrantsErrors,
  PostApiV2PermissionsQueryPersonalGrantsResponses,
  PostApiV2PermissionsQueryPersonsGrantsData,
  PostApiV2PermissionsQueryPersonsGrantsErrors,
  PostApiV2PermissionsQueryPersonsGrantsResponses,
  PostApiV2PermissionsQuerySubordinateEntitiesRolesData,
  PostApiV2PermissionsQuerySubordinateEntitiesRolesErrors,
  PostApiV2PermissionsQuerySubordinateEntitiesRolesResponses,
  PostApiV2PermissionsQuerySubunitsGrantsData,
  PostApiV2PermissionsQuerySubunitsGrantsErrors,
  PostApiV2PermissionsQuerySubunitsGrantsResponses,
  PostApiV2PermissionsSubunitsGrantsData,
  PostApiV2PermissionsSubunitsGrantsErrors,
  PostApiV2PermissionsSubunitsGrantsResponses,
  PostApiV2SessionsBatchByReferenceNumberCloseData,
  PostApiV2SessionsBatchByReferenceNumberCloseErrors,
  PostApiV2SessionsBatchByReferenceNumberCloseResponses,
  PostApiV2SessionsBatchData,
  PostApiV2SessionsBatchErrors,
  PostApiV2SessionsBatchResponses,
  PostApiV2SessionsOnlineByReferenceNumberCloseData,
  PostApiV2SessionsOnlineByReferenceNumberCloseErrors,
  PostApiV2SessionsOnlineByReferenceNumberCloseResponses,
  PostApiV2SessionsOnlineByReferenceNumberInvoicesData,
  PostApiV2SessionsOnlineByReferenceNumberInvoicesErrors,
  PostApiV2SessionsOnlineByReferenceNumberInvoicesResponses,
  PostApiV2SessionsOnlineData,
  PostApiV2SessionsOnlineErrors,
  PostApiV2SessionsOnlineResponses,
  PostApiV2TestdataAttachmentData,
  PostApiV2TestdataAttachmentErrors,
  PostApiV2TestdataAttachmentResponses,
  PostApiV2TestdataAttachmentRevokeData,
  PostApiV2TestdataAttachmentRevokeErrors,
  PostApiV2TestdataAttachmentRevokeResponses,
  PostApiV2TestdataLimitsContextSessionData,
  PostApiV2TestdataLimitsContextSessionErrors,
  PostApiV2TestdataLimitsContextSessionResponses,
  PostApiV2TestdataLimitsSubjectCertificateData,
  PostApiV2TestdataLimitsSubjectCertificateErrors,
  PostApiV2TestdataLimitsSubjectCertificateResponses,
  PostApiV2TestdataPermissionsData,
  PostApiV2TestdataPermissionsErrors,
  PostApiV2TestdataPermissionsResponses,
  PostApiV2TestdataPermissionsRevokeData,
  PostApiV2TestdataPermissionsRevokeErrors,
  PostApiV2TestdataPermissionsRevokeResponses,
  PostApiV2TestdataPersonData,
  PostApiV2TestdataPersonErrors,
  PostApiV2TestdataPersonRemoveData,
  PostApiV2TestdataPersonRemoveErrors,
  PostApiV2TestdataPersonRemoveResponses,
  PostApiV2TestdataPersonResponses,
  PostApiV2TestdataRateLimitsData,
  PostApiV2TestdataRateLimitsErrors,
  PostApiV2TestdataRateLimitsProductionData,
  PostApiV2TestdataRateLimitsProductionErrors,
  PostApiV2TestdataRateLimitsProductionResponses,
  PostApiV2TestdataRateLimitsResponses,
  PostApiV2TestdataSubjectData,
  PostApiV2TestdataSubjectErrors,
  PostApiV2TestdataSubjectRemoveData,
  PostApiV2TestdataSubjectRemoveErrors,
  PostApiV2TestdataSubjectRemoveResponses,
  PostApiV2TestdataSubjectResponses,
  PostApiV2TokensData,
  PostApiV2TokensErrors,
  PostApiV2TokensResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Pobranie listy aktywnych sesji
 *
 * Zwraca listę aktywnych sesji uwierzytelnienia.
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 */
export const getApiV2AuthSessions = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2AuthSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2AuthSessionsResponses,
    GetApiV2AuthSessionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/auth/sessions',
    ...options,
  });

/**
 * Unieważnienie aktualnej sesji uwierzytelnienia
 *
 * Unieważnia sesję powiązaną z tokenem użytym do wywołania tej operacji.
 *
 * Unieważnienie sesji sprawia, że powiązany z nią refresh token przestaje działać i nie można już za jego pomocą uzyskać kolejnych access tokenów.
 * **Aktywne access tokeny działają do czasu minięcia ich termin ważności.**
 *
 * Sposób uwierzytelnienia: `RefreshToken` lub `AccessToken`.
 */
export const deleteApiV2AuthSessionsCurrent = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiV2AuthSessionsCurrentData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV2AuthSessionsCurrentResponses,
    DeleteApiV2AuthSessionsCurrentErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/auth/sessions/current',
    ...options,
  });

/**
 * Unieważnienie sesji uwierzytelnienia
 *
 * Unieważnia sesję o podanym numerze referencyjnym.
 *
 * Unieważnienie sesji sprawia, że powiązany z nią refresh token przestaje działać i nie można już za jego pomocą uzyskać kolejnych access tokenów.
 * **Aktywne access tokeny działają do czasu minięcia ich termin ważności.**
 */
export const deleteApiV2AuthSessionsByReferenceNumber = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV2AuthSessionsByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiV2AuthSessionsByReferenceNumberResponses,
    DeleteApiV2AuthSessionsByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/auth/sessions/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie danych o limitach certyfikatów
 *
 * Zwraca informacje o limitach certyfikatów oraz informacje czy użytkownik może zawnioskować o certyfikat KSeF.
 */
export const getApiV2CertificatesLimits = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2CertificatesLimitsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2CertificatesLimitsResponses,
    GetApiV2CertificatesLimitsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/limits',
    ...options,
  });

/**
 * Pobranie danych do wniosku certyfikacyjnego
 *
 * Zwraca dane wymagane do przygotowania wniosku certyfikacyjnego PKCS#10.
 *
 * Dane te są zwracane na podstawie certyfikatu użytego w procesie uwierzytelnienia i identyfikują podmiot, który składa wniosek o certyfikat.
 *
 *
 * > Więcej informacji:
 * > - [Pobranie danych do wniosku certyfikacyjnego](https://github.com/CIRFMF/ksef-docs/blob/main/certyfikaty-KSeF.md#2-pobranie-danych-do-wniosku-certyfikacyjnego)
 * > - [Przygotowanie wniosku](https://github.com/CIRFMF/ksef-docs/blob/main/certyfikaty-KSeF.md#3-przygotowanie-csr-certificate-signing-request)
 */
export const getApiV2CertificatesEnrollmentsData = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2CertificatesEnrollmentsDataData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2CertificatesEnrollmentsDataResponses,
    GetApiV2CertificatesEnrollmentsDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/enrollments/data',
    ...options,
  });

/**
 * Wysyłka wniosku certyfikacyjnego
 *
 * Przyjmuje wniosek certyfikacyjny i rozpoczyna jego przetwarzanie.
 *
 * Dozwolone typy kluczy prywatnych:
 * - RSA (OID: 1.2.840.113549.1.1.1), długość klucza równa 2048 bitów,
 * - EC (klucze oparte na krzywych eliptycznych, OID: 1.2.840.10045.2.1), krzywa NIST P-256 (secp256r1)
 *
 * Zalecane jest stosowanie kluczy EC.
 *
 * Dozwolone algorytmy podpisu:
 * - RSA PKCS#1 v1.5,
 * - RSA PSS,
 * - ECDSA (format podpisu zgodny z RFC 3279)
 *
 * Dozwolone funkcje skrótu użyte do podpisu CSR:
 * - SHA1,
 * - SHA256,
 * - SHA384,
 * - SHA512
 *
 * > Więcej informacji:
 * > - [Wysłanie wniosku certyfikacyjnego](https://github.com/CIRFMF/ksef-docs/blob/main/certyfikaty-KSeF.md#4-wys%C5%82anie-wniosku-certyfikacyjnego)
 */
export const postApiV2CertificatesEnrollments = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2CertificatesEnrollmentsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2CertificatesEnrollmentsResponses,
    PostApiV2CertificatesEnrollmentsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/enrollments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie statusu przetwarzania wniosku certyfikacyjnego
 *
 * Zwraca informacje o statusie wniosku certyfikacyjnego.
 */
export const getApiV2CertificatesEnrollmentsByReferenceNumber = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV2CertificatesEnrollmentsByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2CertificatesEnrollmentsByReferenceNumberResponses,
    GetApiV2CertificatesEnrollmentsByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/enrollments/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie certyfikatu lub listy certyfikatów
 *
 * Zwraca certyfikaty o podanych numerach seryjnych w formacie DER zakodowanym w Base64.
 */
export const postApiV2CertificatesRetrieve = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2CertificatesRetrieveData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2CertificatesRetrieveResponses,
    PostApiV2CertificatesRetrieveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/retrieve',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Unieważnienie certyfikatu
 *
 * Unieważnia certyfikat o podanym numerze seryjnym.
 */
export const postApiV2CertificatesByCertificateSerialNumberRevoke = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV2CertificatesByCertificateSerialNumberRevokeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV2CertificatesByCertificateSerialNumberRevokeResponses,
    PostApiV2CertificatesByCertificateSerialNumberRevokeErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/{certificateSerialNumber}/revoke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Pobranie listy metadanych certyfikatów
 *
 * Zwraca listę certyfikatów spełniających podane kryteria wyszukiwania.
 * W przypadku braku podania kryteriów wyszukiwania zwrócona zostanie nieprzefiltrowana lista.
 *
 * **Sortowanie:**
 *
 * - requestDate (Desc)
 *
 *
 */
export const postApiV2CertificatesQuery = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2CertificatesQueryData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2CertificatesQueryResponses,
    PostApiV2CertificatesQueryErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/certificates/query',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie certyfikatów
 *
 * Zwraca informacje o kluczach publicznych używanych do szyfrowania danych przesyłanych do systemu KSeF.
 */
export const getApiV2SecurityPublicKeyCertificates = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2SecurityPublicKeyCertificatesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2SecurityPublicKeyCertificatesResponses,
    GetApiV2SecurityPublicKeyCertificatesErrors,
    ThrowOnError
  >({ url: '/api/v2/security/public-key-certificates', ...options });

/**
 * Utworzenie podmiotu
 *
 * Tworzenie nowego podmiotu testowego. W przypadku grupy VAT i JST istnieje możliwość stworzenia jednostek podrzędnych. W wyniku takiego działania w systemie powstanie powiązanie między tymi podmiotami.
 */
export const postApiV2TestdataSubject = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataSubjectData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataSubjectResponses,
    PostApiV2TestdataSubjectErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/subject',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Usunięcie podmiotu
 *
 * Usuwanie podmiotu testowego. W przypadku grupy VAT i JST usunięte zostaną również jednostki podrzędne.
 */
export const postApiV2TestdataSubjectRemove = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataSubjectRemoveData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataSubjectRemoveResponses,
    PostApiV2TestdataSubjectRemoveErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/subject/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Utworzenie osoby fizycznej
 *
 * Tworzenie nowej osoby fizycznej, której system nadaje uprawnienia właścicielskie. Można również określić, czy osoba ta jest komornikiem – wówczas otrzyma odpowiednie uprawnienie egzekucyjne.
 */
export const postApiV2TestdataPerson = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataPersonData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataPersonResponses,
    PostApiV2TestdataPersonErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/person',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Usunięcie osoby fizycznej
 *
 * Usuwanie testowej osoby fizycznej. System automatycznie odbierze jej wszystkie uprawnienia.
 */
export const postApiV2TestdataPersonRemove = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataPersonRemoveData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataPersonRemoveResponses,
    PostApiV2TestdataPersonRemoveErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/person/remove',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie uprawnień testowemu podmiotowi/osobie fizycznej
 *
 * Nadawanie uprawnień testowemu podmiotowi lub osobie fizycznej, a także w ich kontekście.
 */
export const postApiV2TestdataPermissions = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataPermissionsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataPermissionsResponses,
    PostApiV2TestdataPermissionsErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/permissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Odebranie uprawnień testowemu podmiotowi/osobie fizycznej
 *
 * Odbieranie uprawnień nadanych testowemu podmiotowi lub osobie fizycznej, a także w ich kontekście.
 */
export const postApiV2TestdataPermissionsRevoke = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataPermissionsRevokeData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataPermissionsRevokeResponses,
    PostApiV2TestdataPermissionsRevokeErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/permissions/revoke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Umożliwienie wysyłania faktur z załącznikiem
 *
 * Dodaje możliwość wysyłania faktur z załącznikiem przez wskazany podmiot
 */
export const postApiV2TestdataAttachment = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataAttachmentData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataAttachmentResponses,
    PostApiV2TestdataAttachmentErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/attachment',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Odebranie możliwości wysyłania faktur z załącznikiem
 *
 * Odbiera możliwość wysyłania faktur z załącznikiem przez wskazany podmiot
 */
export const postApiV2TestdataAttachmentRevoke = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataAttachmentRevokeData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataAttachmentRevokeResponses,
    PostApiV2TestdataAttachmentRevokeErrors,
    ThrowOnError
  >({
    url: '/api/v2/testdata/attachment/revoke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie limitów dla bieżącego kontekstu
 *
 * Zwraca wartości aktualnie obowiązujących limitów dla bieżącego kontekstu.
 */
export const getApiV2LimitsContext = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2LimitsContextData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2LimitsContextResponses,
    GetApiV2LimitsContextErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/limits/context',
    ...options,
  });

/**
 * Pobranie limitów dla bieżącego podmiotu
 *
 * Zwraca wartoście aktualnie obowiązujących limitów dla bieżącego podmiotu.
 */
export const getApiV2LimitsSubject = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2LimitsSubjectData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2LimitsSubjectResponses,
    GetApiV2LimitsSubjectErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/limits/subject',
    ...options,
  });

/**
 * Pobranie aktualnie obowiązujących limitów API
 *
 * Zwraca wartości aktualnie obowiązujących limitów ilości żądań przesyłanych do API.
 */
export const getApiV2RateLimits = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2RateLimitsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2RateLimitsResponses,
    GetApiV2RateLimitsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/rate-limits',
    ...options,
  });

/**
 * Przywrócenie domyślnych wartości limitów sesji dla bieżącego kontekstu
 *
 * Przywraca wartości aktualnie obowiązujących limitów sesji dla bieżącego kontekstu do wartości domyślnych. **Tylko na środowiskach testowych.**
 */
export const deleteApiV2TestdataLimitsContextSession = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiV2TestdataLimitsContextSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV2TestdataLimitsContextSessionResponses,
    DeleteApiV2TestdataLimitsContextSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/limits/context/session',
    ...options,
  });

/**
 * Zmiana limitów sesji dla bieżącego kontekstu
 *
 * Zmienia wartości aktualnie obowiązujących limitów sesji dla bieżącego kontekstu. **Tylko na środowiskach testowych.**
 */
export const postApiV2TestdataLimitsContextSession = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataLimitsContextSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataLimitsContextSessionResponses,
    PostApiV2TestdataLimitsContextSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/limits/context/session',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Przywrócenie domyślnych wartości limitów certyfikatów dla bieżącego podmiotu
 *
 * Przywraca wartości aktualnie obowiązujących limitów certyfikatów dla bieżącego podmiotu do wartości domyślnych. **Tylko na środowiskach testowych.**
 */
export const deleteApiV2TestdataLimitsSubjectCertificate = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiV2TestdataLimitsSubjectCertificateData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV2TestdataLimitsSubjectCertificateResponses,
    DeleteApiV2TestdataLimitsSubjectCertificateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/limits/subject/certificate',
    ...options,
  });

/**
 * Zmiana limitów certyfikatów dla bieżącego podmiotu
 *
 * Zmienia wartości aktualnie obowiązujących limitów certyfikatów dla bieżącego podmiotu. **Tylko na środowiskach testowych.**
 */
export const postApiV2TestdataLimitsSubjectCertificate = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataLimitsSubjectCertificateData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataLimitsSubjectCertificateResponses,
    PostApiV2TestdataLimitsSubjectCertificateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/limits/subject/certificate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Przywrócenie domyślnych wartości limitów API dla bieżącego kontekstu
 *
 * Przywraca wartości aktualnie obowiązujących limitów żądań przesyłąnych do API dla bieżącego kontekstu do wartości domyślnych. **Tylko na środowiskach testowych.**
 */
export const deleteApiV2TestdataRateLimits = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiV2TestdataRateLimitsData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV2TestdataRateLimitsResponses,
    DeleteApiV2TestdataRateLimitsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/rate-limits',
    ...options,
  });

/**
 * Zmiana limitów API dla bieżącego kontekstu
 *
 * Zmienia wartości aktualnie obowiązujących limitów żądań przesyłąnych do API dla bieżącego kontekstu. **Tylko na środowiskach testowych.**
 */
export const postApiV2TestdataRateLimits = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataRateLimitsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataRateLimitsResponses,
    PostApiV2TestdataRateLimitsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/rate-limits',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Zmiana limitów API dla bieżącego kontekstu na wartości produkcyjne
 *
 * Zmienia wartości aktualnie obowiązujących limitów żądań przesyłanych do API dla bieżącego kontekstu na wartości takie jakie będą na środowisku produkcyjnym. **Tylko na środowiskach testowych.**
 */
export const postApiV2TestdataRateLimitsProduction = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TestdataRateLimitsProductionData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2TestdataRateLimitsProductionResponses,
    PostApiV2TestdataRateLimitsProductionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/testdata/rate-limits/production',
    ...options,
  });

/**
 * Nadanie osobom fizycznym uprawnień do pracy w KSeF
 *
 * Metoda pozwala na nadanie osobie wskazanej w żądaniu uprawnień do pracy w KSeF
 * w kontekście bieżącym.
 *
 * W żądaniu określane są nadawane uprawnienia ze zbioru:
 * - **InvoiceWrite** – wystawianie faktur,
 * - **InvoiceRead** – przeglądanie faktur,
 * - **CredentialsManage** – zarządzanie uprawnieniami,
 * - **CredentialsRead** – przeglądanie uprawnień,
 * - **Introspection** – przeglądanie historii sesji i generowanie UPO,
 * - **SubunitManage** – zarządzanie jednostkami podrzędnymi,
 * - **EnforcementOperations** – wykonywanie operacji egzekucyjnych.
 *
 * Metoda pozwala na wybór dowolnej kombinacji powyższych uprawnień.
 * Uprawnienie **EnforcementOperations** może być nadane wyłącznie wtedy,
 * gdy podmiot kontekstu ma rolę **EnforcementAuthority** (organ egzekucyjny)
 * lub **CourtBailiff** (komornik sądowy).
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadawanie-uprawnie%C5%84-osobom-fizycznym-do-pracy-w-ksef)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`.
 */
export const postApiV2PermissionsPersonsGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsPersonsGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsPersonsGrantsResponses,
    PostApiV2PermissionsPersonsGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/persons/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie podmiotom uprawnień do obsługi faktur
 *
 * Metoda pozwala na nadanie podmiotowi wskazanemu w żądaniu uprawnień do obsługi faktur podmiotu kontekstu.
 * W żądaniu określane są nadawane uprawnienia ze zbioru:
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 *
 * Metoda pozwala na wybór dowolnej kombinacji powyższych uprawnień.
 * Dla każdego uprawnienia może być ustawiona flaga **canDelegate**, mówiąca o możliwości jego dalszego przekazywania poprzez nadawanie w sposób pośredni.
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadanie-podmiotom-uprawnie%C5%84-do-obs%C5%82ugi-faktur)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`.
 */
export const postApiV2PermissionsEntitiesGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsEntitiesGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsEntitiesGrantsResponses,
    PostApiV2PermissionsEntitiesGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/entities/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie uprawnień podmiotowych
 *
 * Metoda pozwala na nadanie jednego z uprawnień podmiotowych do obsługi podmiotu kontekstu  podmiotowi wskazanemu w żądaniu.
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadanie-uprawnie%C5%84-podmiotowych)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`.
 */
export const postApiV2PermissionsAuthorizationsGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsAuthorizationsGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsAuthorizationsGrantsResponses,
    PostApiV2PermissionsAuthorizationsGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/authorizations/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie uprawnień w sposób pośredni
 *
 * Metoda pozwala na nadanie w sposób pośredni osobie wskazanej w żądaniu uprawnień do obsługi faktur innego podmiotu – klienta.
 * Może to być jedna z możliwości:
 * - nadanie uprawnień generalnych – do obsługi wszystkich klientów
 * - nadanie uprawnień selektywnych – do obsługi wskazanego klienta
 *
 * Uprawnienie selektywne może być nadane wyłącznie wtedy, gdy klient nadał wcześniej podmiotowi bieżącego kontekstu dowolne uprawnienie z prawem do jego dalszego przekazywania (patrz [POST /api/v2/permissions/entities/grants](/docs/v2/index.html#tag/Nadawanie-uprawnien/paths/~1api~1v2~1permissions~1entities~1grants/post)).
 *
 * W żądaniu określane są nadawane uprawnienia ze zbioru:
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 *
 * Metoda pozwala na wybór dowolnej kombinacji powyższych uprawnień.
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadanie-uprawnie%C5%84-w-spos%C3%B3b-po%C5%9Bredni)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`.
 */
export const postApiV2PermissionsIndirectGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsIndirectGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsIndirectGrantsResponses,
    PostApiV2PermissionsIndirectGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/indirect/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie uprawnień administratora podmiotu podrzędnego
 *
 * Metoda pozwala na nadanie wskazanemu w żądaniu podmiotowi lub osobie fizycznej uprawnień administratora w kontekście:
 * - wskazanego NIP podmiotu podrzędnego – wyłącznie jeżeli podmiot bieżącego kontekstu logowania ma rolę podmiotu nadrzędnego:
 * - **LocalGovernmentUnit**
 * - **VatGroupUnit**
 * - wskazanego lub utworzonego identyfikatora wewnętrznego
 *
 * Wraz z utworzeniem administratora jednostki podrzędnej tworzony jest identyfikator wewnętrzny składający się z numeru NIP podmiotu kontekstu logowania oraz 5 cyfr unikalnie identyfikujących jednostkę wewnętrzną.
 * W żądaniu podaje się również nazwę tej jednostki.
 *
 * Uprawnienia administratora jednostki podrzędnej obejmują:
 * - **CredentialsManage** – zarządzanie uprawnieniami
 *
 * Metoda automatycznie nadaje powyższe uprawnienie, bez konieczności podawania go w żądaniu.
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadanie-uprawnie%C5%84-administratora-podmiotu-podrz%C4%99dnego)
 *
 * **Wymagane uprawnienia**: `SubunitManage`.
 */
export const postApiV2PermissionsSubunitsGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsSubunitsGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsSubunitsGrantsResponses,
    PostApiV2PermissionsSubunitsGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/subunits/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie uprawnień administratora podmiotu unijnego
 *
 * Metoda pozwala na nadanie wskazanemu w żądaniu podmiotowi lub osobie fizycznej uprawnień administratora w kontekście złożonym z identyfikatora NIP podmiotu kontekstu bieżącego oraz numeru VAT UE podmiotu unijnego wskazanego w żądaniu.
 * Wraz z utworzeniem administratora podmiotu unijnego tworzony jest kontekst złożony składający się z numeru NIP podmiotu kontekstu logowania oraz wskazanego numeru identyfikacyjnego VAT UE podmiotu unijnego.
 * W żądaniu podaje się również nazwę i adres podmiotu unijnego.
 *
 * Jedynym sposobem identyfikacji uprawnianego jest odcisk palca certyfikatu kwalifikowanego:
 * - certyfikat podpisu elektronicznego dla osób fizycznych
 * - certyfikat pieczęci elektronicznej dla podmiotów
 *
 * Uprawnienia administratora podmiotu unijnego obejmują:
 * - **VatEuManage** – zarządzanie uprawnieniami w ramach podmiotu unijnego
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 * - **Introspection** – przeglądanie historii sesji
 *
 * Metoda automatycznie nadaje wszystkie powyższe uprawnienia, bez konieczności ich wskazywania w żądaniu.
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadanie-uprawnie%C5%84-administratora-podmiotu-unijnego)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`.
 */
export const postApiV2PermissionsEuEntitiesAdministrationGrants = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiV2PermissionsEuEntitiesAdministrationGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsEuEntitiesAdministrationGrantsResponses,
    PostApiV2PermissionsEuEntitiesAdministrationGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/eu-entities/administration/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Nadanie uprawnień reprezentanta podmiotu unijnego
 *
 * Metoda pozwala na nadanie wskazanemu w żądaniu podmiotowi lub osobie fizycznej uprawnień do wystawiania i/lub przeglądania faktur w kontekście złożonym kontekstu bieżącego.
 *
 * Jedynym sposobem identyfikacji uprawnianego jest odcisk palca certyfikatu kwalifikowanego:
 * - certyfikat podpisu elektronicznego dla osób fizycznych
 * - certyfikat pieczęci elektronicznej dla podmiotów
 *
 * W żądaniu określane są nadawane uprawnienia ze zbioru:
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 *
 * Metoda pozwala na wybór dowolnej kombinacji powyższych uprawnień.
 *
 * > Więcej informacji:
 * > - [Nadawanie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#nadanie-uprawnie%C5%84-reprezentanta-podmiotu-unijnego)
 *
 * **Wymagane uprawnienia**: `VatUeManage`.
 */
export const postApiV2PermissionsEuEntitiesGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsEuEntitiesGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsEuEntitiesGrantsResponses,
    PostApiV2PermissionsEuEntitiesGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/eu-entities/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Odebranie uprawnień
 *
 * Metoda pozwala na odebranie uprawnienia o wskazanym identyfikatorze.
 * Wymagane jest wcześniejsze odczytanie uprawnień w celu uzyskania
 * identyfikatora uprawnienia, które ma zostać odebrane.
 *
 * > Więcej informacji:
 * > - [Odbieranie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#odebranie-uprawnie%C5%84)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `VatUeManage`, `SubunitManage`.
 */
export const deleteApiV2PermissionsCommonGrantsByPermissionId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiV2PermissionsCommonGrantsByPermissionIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiV2PermissionsCommonGrantsByPermissionIdResponses,
    DeleteApiV2PermissionsCommonGrantsByPermissionIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/common/grants/{permissionId}',
    ...options,
  });

/**
 * Odebranie uprawnień podmiotowych
 *
 * Metoda pozwala na odebranie uprawnienia podmiotowego o wskazanym identyfikatorze.
 * Wymagane jest wcześniejsze odczytanie uprawnień w celu uzyskania
 * identyfikatora uprawnienia, które ma zostać odebrane.
 *
 * > Więcej informacji:
 * > - [Odbieranie uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#odebranie-uprawnie%C5%84-podmiotowych)
 *
 * **Wymagane uprawnienia**: `CredentialsManage`.
 */
export const deleteApiV2PermissionsAuthorizationsGrantsByPermissionId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiV2PermissionsAuthorizationsGrantsByPermissionIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiV2PermissionsAuthorizationsGrantsByPermissionIdResponses,
    DeleteApiV2PermissionsAuthorizationsGrantsByPermissionIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/authorizations/grants/{permissionId}',
    ...options,
  });

/**
 * Pobranie statusu operacji
 *
 * Zwraca status operacji asynchronicznej związanej z nadaniem lub odebraniem uprawnień.
 */
export const getApiV2PermissionsOperationsByReferenceNumber = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV2PermissionsOperationsByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2PermissionsOperationsByReferenceNumberResponses,
    GetApiV2PermissionsOperationsByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/operations/{referenceNumber}',
    ...options,
  });

/**
 * Sprawdzenie statusu zgody na wystawianie faktur z załącznikiem
 *
 * Sprawdzenie czy obecny kontekst posiada zgodę na wystawianie faktur z załącznikiem.
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`.
 */
export const getApiV2PermissionsAttachmentsStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2PermissionsAttachmentsStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2PermissionsAttachmentsStatusResponses,
    GetApiV2PermissionsAttachmentsStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/attachments/status',
    ...options,
  });

/**
 * Pobranie faktury po numerze KSeF
 *
 * Zwraca fakturę o podanym numerze KSeF.
 *
 * **Wymagane uprawnienia**: `InvoiceRead`.
 */
export const getApiV2InvoicesKsefByKsefNumber = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2InvoicesKsefByKsefNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2InvoicesKsefByKsefNumberResponses,
    GetApiV2InvoicesKsefByKsefNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/invoices/ksef/{ksefNumber}',
    ...options,
  });

/**
 * Pobranie listy metadanych faktur
 *
 * Zwraca metadane faktur spełniających filtry.
 *
 * Limit techniczny: ≤ 10 000 rekordów na zestaw filtrów, po jego osiągnięciu <b>isTruncated = true</b> i należy ponownie ustawić <b>dateRange</b>, używając ostatniej daty z wyników (tj. ustawić from/to - w zależności od kierunku sortowania, od daty ostatniego zwróconego rekordu) oraz wyzerować <b>pageOffset</b>.
 *
 * `Do scenariusza przyrostowego należy używać daty PermanentStorage oraz kolejność sortowania Asc`.
 *
 * <b>Scenariusz pobierania przyrostowego (skrót):</b>
 * * Gdy <b>hasMore = false</b>, należy zakończyć,
 * * Gdy <b>hasMore = true</b> i <b>isTruncated = false</b>, należy zwiększyć <b>pageOffset</b>,
 * * Gdy <b>hasMore = true</b> i <b>isTruncated = true</b>, należy zawęzić <b>dateRange</b> (ustawić from od daty ostatniego rekordu), wyzerować <b>pageOffset</b> i kontynuować
 *
 * **Sortowanie:**
 *
 * - permanentStorageDate | invoicingDate | issueDate (Asc | Desc) - pole wybierane na podstawie filtrów
 *
 *
 *
 * **Wymagane uprawnienia**: `InvoiceRead`.
 */
export const postApiV2InvoicesQueryMetadata = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2InvoicesQueryMetadataData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2InvoicesQueryMetadataResponses,
    PostApiV2InvoicesQueryMetadataErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/invoices/query/metadata',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Eksport paczki faktur
 *
 * Rozpoczyna asynchroniczny proces wyszukiwania faktur w systemie KSeF na podstawie przekazanych filtrów oraz przygotowania ich w formie zaszyfrowanej paczki.
 * Wymagane jest przekazanie informacji o szyfrowaniu w polu <b>Encryption</b>, które służą do zabezpieczenia przygotowanej paczki z fakturami.
 * Maksymalnie można uruchomić 10 równoczesnych eksportów w zalogowanym kontekście.
 *
 * System pobiera faktury rosnąco według daty określonej w filtrze (Invoicing, Issue, PermanentStorage) i dodaje faktury(nazwa pliku: <b>{ksefNumber}.xml</b>) do paczki aż do osiągnięcia jednego z poniższych limitów:
 * * Limit liczby faktur: 10 000 sztuk
 * * Limit rozmiaru danych(skompresowanych): 1GB
 *
 * Paczka eksportu zawiera dodatkowy plik z metadanymi faktur w formacie JSON (`_metadata.json`). Zawartość pliku to
 * obiekt z tablicą <b>invoices</b>, gdzie każdy element jest obiektem typu <b>InvoiceMetadata</b>
 * (taki jak zwracany przez endpoint `POST /invoices/query/metadata`).
 *
 * <b>Plik z metadanymi(_metadata.json) nie jest wliczany do limitów algorytmu budowania paczki</b>.
 *
 * `Do realizacji pobierania przyrostowego należy stosować filtrowanie po dacie PermanentStorage`.
 *
 * **Sortowanie:**
 *
 * - permanentStorageDate | invoicingDate | issueDate (Asc) - pole wybierane na podstawie filtrów
 *
 *
 *
 * **Wymagane uprawnienia**: `InvoiceRead`.
 */
export const postApiV2InvoicesExports = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2InvoicesExportsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2InvoicesExportsResponses,
    PostApiV2InvoicesExportsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/invoices/exports',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie statusu eksportu paczki faktur
 *
 * Paczka faktur jest dzielona na części o maksymalnym rozmiarze 50 MB. Każda część jest zaszyfrowana algorytmem AES-256-CBC z dopełnieniem PKCS#7, przy użyciu klucza symetrycznego przekazanego podczas inicjowania eksportu.
 *
 * W przypadku ucięcia wyniku eksportu z powodu przekroczenia limitów, zwracana jest flaga <b>IsTruncated = true</b> oraz odpowiednia data, którą należy wykorzystać do wykonania kolejnego eksportu, aż do momentu, gdy flaga <b>IsTruncated = false</b>.
 *
 * **Sortowanie:**
 *
 * - permanentStorageDate | invoicingDate | issueDate (Asc) - pole wybierane na podstawie filtrów
 *
 *
 *
 * **Wymagane uprawnienia**: `InvoiceRead`.
 */
export const getApiV2InvoicesExportsByReferenceNumber = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2InvoicesExportsByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2InvoicesExportsByReferenceNumberResponses,
    GetApiV2InvoicesExportsByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/invoices/exports/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie listy sesji
 *
 * Zwraca listę sesji spełniających podane kryteria wyszukiwania.
 *
 *
 *
 * **Sortowanie:**
 *
 * - dateCreated (Desc)
 *
 *
 * **Wymagane uprawnienia**:
 * - `Introspection` – pozwala pobrać wszystkie sesje w bieżącym kontekście uwierzytelnienia `(ContextIdentifier)`.
 * - `InvoiceWrite` – pozwala pobrać wyłącznie sesje utworzone przez podmiot uwierzytelniający, czyli podmiot inicjujący uwierzytelnienie.
 */
export const getApiV2Sessions = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2SessionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiV2SessionsResponses, GetApiV2SessionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions',
    ...options,
  });

/**
 * Pobranie statusu sesji
 *
 * Sprawdza bieżący status sesji o podanym numerze referencyjnym.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumber = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2SessionsByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberResponses,
    GetApiV2SessionsByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie faktur sesji
 *
 * Zwraca listę faktur przesłanych w sesji wraz z ich statusami, oraz informacje na temat ilości poprawnie i niepoprawnie przetworzonych faktur.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumberInvoices = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2SessionsByReferenceNumberInvoicesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberInvoicesResponses,
    GetApiV2SessionsByReferenceNumberInvoicesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}/invoices',
    ...options,
  });

/**
 * Pobranie statusu faktury z sesji
 *
 * Zwraca fakturę przesłaną w sesji wraz ze statusem.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumber = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberResponses,
    GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}/invoices/{invoiceReferenceNumber}',
    ...options,
  });

/**
 * Pobranie niepoprawnie przetworzonych faktur sesji
 *
 * Zwraca listę niepoprawnie przetworzonych faktur przesłanych w sesji wraz z ich statusami.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumberInvoicesFailed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV2SessionsByReferenceNumberInvoicesFailedData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberInvoicesFailedResponses,
    GetApiV2SessionsByReferenceNumberInvoicesFailedErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}/invoices/failed',
    ...options,
  });

/**
 * Pobranie UPO faktury z sesji na podstawie numeru KSeF
 *
 * Zwraca UPO faktury przesłanego w sesji na podstawie jego numeru KSeF.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpo = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpoData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpoResponses,
    GetApiV2SessionsByReferenceNumberInvoicesKsefByKsefNumberUpoErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}/invoices/ksef/{ksefNumber}/upo',
    ...options,
  });

/**
 * Pobranie UPO faktury z sesji na podstawie numeru referencyjnego faktury
 *
 * Zwraca UPO faktury przesłanego w sesji na podstawie jego numeru KSeF.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpo = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpoData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpoResponses,
    GetApiV2SessionsByReferenceNumberInvoicesByInvoiceReferenceNumberUpoErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}/invoices/{invoiceReferenceNumber}/upo',
    ...options,
  });

/**
 * Pobranie UPO dla sesji
 *
 * Zwraca XML zawierający zbiorcze UPO dla sesji.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `Introspection`, `PefInvoiceWrite`.
 */
export const getApiV2SessionsByReferenceNumberUpoByUpoReferenceNumber = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV2SessionsByReferenceNumberUpoByUpoReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2SessionsByReferenceNumberUpoByUpoReferenceNumberResponses,
    GetApiV2SessionsByReferenceNumberUpoByUpoReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/{referenceNumber}/upo/{upoReferenceNumber}',
    ...options,
  });

/**
 * Pobranie listy wygenerowanych tokenów
 *
 *
 *
 * **Sortowanie:**
 *
 * - dateCreated (Desc)
 *
 *
 */
export const getApiV2Tokens = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2TokensData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiV2TokensResponses, GetApiV2TokensErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/tokens',
    ...options,
  });

/**
 * Wygenerowanie nowego tokena
 *
 * Zwraca token, który może być użyty do uwierzytelniania się w KSeF.
 *
 * Token może być generowany tylko w kontekście NIP lub identyfikatora wewnętrznego. Jest zwracany tylko raz. Zaczyna być aktywny w momencie gdy jego status zmieni się na `Active`.
 */
export const postApiV2Tokens = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2TokensData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostApiV2TokensResponses, PostApiV2TokensErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/tokens',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Unieważnienie tokena
 *
 * Unieważniony token nie pozwoli już na uwierzytelnienie się za jego pomocą. Unieważnienie nie może zostać cofnięte.
 */
export const deleteApiV2TokensByReferenceNumber = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV2TokensByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiV2TokensByReferenceNumberResponses,
    DeleteApiV2TokensByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/tokens/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie statusu tokena
 */
export const getApiV2TokensByReferenceNumber = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2TokensByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2TokensByReferenceNumberResponses,
    GetApiV2TokensByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/tokens/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie listy dostawców usług Peppol
 *
 * Zwraca listę dostawców usług Peppol zarejestrowanych w systemie.
 *
 * **Sortowanie:**
 *
 * - dateCreated (Desc)
 *
 *
 */
export const getApiV2PeppolQuery = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2PeppolQueryData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2PeppolQueryResponses,
    GetApiV2PeppolQueryErrors,
    ThrowOnError
  >({ url: '/api/v2/peppol/query', ...options });

/**
 * Inicjalizacja uwierzytelnienia
 *
 * Generuje unikalny challenge wymagany w kolejnym kroku operacji uwierzytelnienia.
 */
export const postApiV2AuthChallenge = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2AuthChallengeData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2AuthChallengeResponses,
    PostApiV2AuthChallengeErrors,
    ThrowOnError
  >({ url: '/api/v2/auth/challenge', ...options });

/**
 * Uwierzytelnienie z wykorzystaniem podpisu XAdES
 *
 * Rozpoczyna operację uwierzytelniania za pomocą dokumentu XML podpisanego podpisem elektronicznym XAdES.
 *
 * > Więcej informacji:
 * > - [Przygotowanie dokumentu XML](https://github.com/CIRFMF/ksef-docs/blob/main/uwierzytelnianie.md#1-przygotowanie-dokumentu-xml-authtokenrequest)
 * > - [Podpis dokumentu XML](https://github.com/CIRFMF/ksef-docs/blob/main/uwierzytelnianie.md#2-podpisanie-dokumentu-xades)
 * > - [Schemat XSD](/docs/v2/schemas/authv2.xsd)
 */
export const postApiV2AuthXadesSignature = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV2AuthXadesSignatureData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV2AuthXadesSignatureResponses,
    PostApiV2AuthXadesSignatureErrors,
    ThrowOnError
  >({
    url: '/api/v2/auth/xades-signature',
    ...options,
    headers: {
      'Content-Type': 'application/xml',
      ...options.headers,
    },
  });

/**
 * Uwierzytelnienie z wykorzystaniem tokena KSeF
 *
 * Rozpoczyna operację uwierzytelniania z wykorzystaniem wcześniej wygenerowanego tokena KSeF.
 *
 * Token KSeF wraz z timestampem ze wcześniej wygenerowanego challenge'a (w formacie ```token|timestamp```) powinien zostać zaszyfrowany dedykowanym do tego celu kluczem publicznym.
 * - Timestamp powinien zostać przekazany jako **liczba milisekund od 1 stycznia 1970 roku (Unix timestamp)**.
 * - Algorytm szyfrowania: **RSA-OAEP (z użyciem SHA-256 jako funkcji skrótu)**.
 */
export const postApiV2AuthKsefToken = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2AuthKsefTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2AuthKsefTokenResponses,
    PostApiV2AuthKsefTokenErrors,
    ThrowOnError
  >({
    url: '/api/v2/auth/ksef-token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie statusu uwierzytelniania
 *
 * Sprawdza bieżący status operacji uwierzytelniania dla podanego tokena.
 *
 * Sposób uwierzytelnienia: `AuthenticationToken` otrzymany przy rozpoczęciu operacji uwierzytelniania.
 */
export const getApiV2AuthByReferenceNumber = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV2AuthByReferenceNumberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV2AuthByReferenceNumberResponses,
    GetApiV2AuthByReferenceNumberErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/auth/{referenceNumber}',
    ...options,
  });

/**
 * Pobranie tokenów dostępowych
 *
 * Pobiera parę tokenów (access token i refresh token) wygenerowanych w ramach pozytywnie zakończonego procesu uwierzytelniania.
 * **Tokeny można pobrać tylko raz.**
 *
 * Sposób uwierzytelnienia: `AuthenticationToken` otrzymany przy rozpoczęciu operacji uwierzytelniania.
 */
export const postApiV2AuthTokenRedeem = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2AuthTokenRedeemData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2AuthTokenRedeemResponses,
    PostApiV2AuthTokenRedeemErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/auth/token/redeem',
    ...options,
  });

/**
 * Odświeżenie tokena dostępowego
 *
 * Generuje nowy token dostępu na podstawie ważnego refresh tokena.
 *
 * Sposób uwierzytelnienia: `RefreshToken`.
 */
export const postApiV2AuthTokenRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2AuthTokenRefreshData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2AuthTokenRefreshResponses,
    PostApiV2AuthTokenRefreshErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/auth/token/refresh',
    ...options,
  });

/**
 * Otwarcie sesji interaktywnej
 *
 * Otwiera sesję do wysyłki pojedynczych faktur. Należy przekazać schemat wysyłanych faktur oraz informacje o kluczu używanym do szyfrowania.
 *
 * > Więcej informacji:
 * > - [Otwarcie sesji interaktywnej](https://github.com/CIRFMF/ksef-docs/blob/main/sesja-interaktywna.md#1-otwarcie-sesji)
 * > - [Klucz publiczny Ministersta Finansów](/docs/v2/index.html#tag/Certyfikaty-klucza-publicznego)
 *
 * Aby generować dokumenty UPO w wersji v4-3 w ramach sesji, należy przy jej otwarciu przesłać nagłówek <b>X-KSeF-Feature: upo-v4-3</b>.
 * Od 22 grudnia 2025 wersja UPO v4-3 będzie generowana domyślnie.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `PefInvoiceWrite`.
 */
export const postApiV2SessionsOnline = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2SessionsOnlineData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2SessionsOnlineResponses,
    PostApiV2SessionsOnlineErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/online',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Wysłanie faktury
 *
 * Przyjmuje zaszyfrowaną fakturę oraz jej metadane i rozpoczyna jej przetwarzanie.
 *
 * > Więcej informacji:
 * > - [Wysłanie faktury](https://github.com/CIRFMF/ksef-docs/blob/main/sesja-interaktywna.md#2-wys%C5%82anie-faktury)
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `PefInvoiceWrite`.
 */
export const postApiV2SessionsOnlineByReferenceNumberInvoices = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV2SessionsOnlineByReferenceNumberInvoicesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV2SessionsOnlineByReferenceNumberInvoicesResponses,
    PostApiV2SessionsOnlineByReferenceNumberInvoicesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/online/{referenceNumber}/invoices',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Zamknięcie sesji interaktywnej
 *
 * Zamyka sesję interaktywną i rozpoczyna generowanie zbiorczego UPO dla sesji.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`, `PefInvoiceWrite`.
 */
export const postApiV2SessionsOnlineByReferenceNumberClose = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV2SessionsOnlineByReferenceNumberCloseData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV2SessionsOnlineByReferenceNumberCloseResponses,
    PostApiV2SessionsOnlineByReferenceNumberCloseErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/online/{referenceNumber}/close',
    ...options,
  });

/**
 * Otwarcie sesji wsadowej
 *
 * Otwiera sesję do wysyłki wsadowej faktur. Należy przekazać schemat wysyłanych faktur, informacje o paczce faktur oraz informacje o kluczu używanym do szyfrowania.
 *
 * > Więcej informacji:
 * > - [Przygotwanie paczki faktur](https://github.com/CIRFMF/ksef-docs/blob/main/sesja-wsadowa.md)
 * > - [Klucz publiczny Ministersta Finansów](/docs/v2/index.html#tag/Certyfikaty-klucza-publicznego)
 *
 * Aby generować dokumenty UPO w wersji v4-3 w ramach sesji, należy przy jej otwarciu przesłać nagłówek <b>X-KSeF-Feature: upo-v4-3</b>.
 * Od 22 grudnia 2025 wersja UPO v4-3 będzie generowana domyślnie.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`.
 */
export const postApiV2SessionsBatch = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2SessionsBatchData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2SessionsBatchResponses,
    PostApiV2SessionsBatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Zamknięcie sesji wsadowej
 *
 * Zamyka sesję wsadową, rozpoczyna procesowanie paczki faktur i generowanie UPO dla prawidłowych faktur oraz zbiorczego UPO dla sesji.
 *
 * **Wymagane uprawnienia**: `InvoiceWrite`.
 */
export const postApiV2SessionsBatchByReferenceNumberClose = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV2SessionsBatchByReferenceNumberCloseData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV2SessionsBatchByReferenceNumberCloseResponses,
    PostApiV2SessionsBatchByReferenceNumberCloseErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/sessions/batch/{referenceNumber}/close',
    ...options,
  });

/**
 * Pobranie listy własnych uprawnień
 *
 *  Metoda pozwala na odczytanie własnych uprawnień uwierzytelnionego klienta API w bieżącym kontekście logowania.
 *
 * W odpowiedzi przekazywane są następujące uprawnienia:
 * - nadane w sposób bezpośredni w bieżącym kontekście
 * - nadane przez podmiot nadrzędny
 * - nadane w sposób pośredni, jeżeli podmiot kontekstu logowania jest w uprawnieniu pośrednikiem lub podmiotem docelowym
 * - nadane podmiotowi do obsługi faktur przez inny podmiot, jeśli podmiot uwierzytelniony ma w bieżącym kontekście uprawnienia właścicielskie
 *
 * Uprawnienia zwracane przez operację obejmują:
 * - **CredentialsManage** – zarządzanie uprawnieniami
 * - **CredentialsRead** – przeglądanie uprawnień
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 * - **Introspection** – przeglądanie historii sesji
 * - **SubunitManage** – zarządzanie podmiotami podrzędnymi
 * - **EnforcementOperations** – wykonywanie operacji egzekucyjnych
 * - **VatEuManage** – zarządzanie uprawnieniami w ramach podmiotu unijnego
 *
 * Odpowiedź może być filtrowana na podstawie następujących parametrów:
 * - **contextIdentifier** – identyfikator podmiotu, który nadał uprawnienie do obsługi faktur
 * - **targetIdentifier** – identyfikator podmiotu docelowego dla uprawnień nadanych pośrednio
 * - **permissionTypes** – lista rodzajów wyszukiwanych uprawnień
 * - **permissionState** – status uprawnienia
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-w%C5%82asnych-uprawnie%C5%84)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 */
export const postApiV2PermissionsQueryPersonalGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsQueryPersonalGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsQueryPersonalGrantsResponses,
    PostApiV2PermissionsQueryPersonalGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/personal/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie listy uprawnień do pracy w KSeF nadanych osobom fizycznym lub podmiotom
 *
 *  Metoda pozwala na odczytanie uprawnień nadanych osobie fizycznej lub podmiotowi.
 * Lista pobranych uprawnień może być dwóch rodzajów:
 * - Lista wszystkich uprawnień obowiązujących w bieżącym kontekście logowania (używana, gdy administrator chce przejrzeć uprawnienia wszystkich użytkowników w bieżącym kontekście)
 * - Lista wszystkich uprawnień nadanych w bieżącym kontekście przez uwierzytelnionego klienta API (używana, gdy administrator chce przejrzeć listę nadanych przez siebie uprawnień w bieżącym kontekście)
 *
 * Dla pierwszej listy (obowiązujących uprawnień) w odpowiedzi przekazywane są:
 * - osoby i podmioty mogące pracować w bieżącym kontekście z wyjątkiem osób uprawnionych w sposób pośredni
 * - osoby uprawnione w sposób pośredni przez podmiot bieżącego kontekstu
 *
 * Dla drugiej listy (nadanych uprawnień) w odpowiedzi przekazywane są:
 * - uprawnienia nadane w sposób bezpośredni do pracy w bieżącym kontekście lub w kontekście jednostek podrzędnych
 * - uprawnienia nadane w sposób pośredni do obsługi klientów podmiotu bieżącego kontekstu
 *
 * Uprawnienia zwracane przez operację obejmują:
 * - **CredentialsManage** – zarządzanie uprawnieniami
 * - **CredentialsRead** – przeglądanie uprawnień
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 * - **Introspection** – przeglądanie historii sesji
 * - **SubunitManage** – zarządzanie podmiotami podrzędnymi
 * - **EnforcementOperations** – wykonywanie operacji egzekucyjnych
 *
 * Odpowiedź może być filtrowana na podstawie parametrów:
 * - **authorIdentifier** – identyfikator osoby, która nadała uprawnienie
 * - **authorizedIdentifier** – identyfikator osoby lub podmiotu uprawnionego
 * - **targetIdentifier** – identyfikator podmiotu docelowego dla uprawnień nadanych pośrednio
 * - **permissionTypes** – lista rodzajów wyszukiwanych uprawnień
 * - **permissionState** – status uprawnienia
 * - **queryType** – typ zapytania określający, która z dwóch list ma zostać zwrócona
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-uprawnie%C5%84-do-pracy-w-ksef-nadanych-osobom-fizycznym-lub-podmiotom)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`, `SubunitManage`.
 */
export const postApiV2PermissionsQueryPersonsGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsQueryPersonsGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsQueryPersonsGrantsResponses,
    PostApiV2PermissionsQueryPersonsGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/persons/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie listy uprawnień administratorów jednostek i podmiotów podrzędnych
 *
 *  Metoda pozwala na odczytanie uprawnień do zarządzania uprawnieniami nadanych administratorom:
 * - jednostek podrzędnych identyfikowanych identyfikatorem wewnętrznym
 * - podmiotów podrzędnych (podrzędnych JST lub członków grupy VAT) identyfikowanych przez NIP
 *
 * Lista zwraca wyłącznie uprawnienia do zarządzania uprawnieniami nadane z kontekstu bieżącego (z podmiotu nadrzędnego).
 * Nie są odczytywane uprawnienia nadane przez administratorów jednostek podrzędnych wewnątrz tych jednostek.
 *
 * Odpowiedź może być filtrowana na podstawie parametru:
 * - **subunitIdentifier** – identyfikator jednostki lub podmiotu podrzędnego
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-uprawnie%C5%84-administrator%C3%B3w-jednostek-i-podmiot%C3%B3w-podrz%C4%99dnych)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`, `SubunitManage`.
 */
export const postApiV2PermissionsQuerySubunitsGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsQuerySubunitsGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsQuerySubunitsGrantsResponses,
    PostApiV2PermissionsQuerySubunitsGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/subunits/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie listy ról podmiotu
 *
 *  Metoda pozwala na **odczytanie listy ról podmiotu bieżącego kontekstu logowania**.
 *
 * #### Role podmiotów zwracane przez operację:
 * - **CourtBailiff** – komornik sądowy
 * - **EnforcementAuthority** – organ egzekucyjny
 * - **LocalGovernmentUnit** – nadrzędna JST
 * - **LocalGovernmentSubUnit** – podrzędne JST
 * - **VatGroupUnit** – grupa VAT
 * - **VatGroupSubUnit** – członek grupy VAT
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy ról](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-r%C3%B3l-podmiotu)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`.
 */
export const getApiV2PermissionsQueryEntitiesRoles = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV2PermissionsQueryEntitiesRolesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV2PermissionsQueryEntitiesRolesResponses,
    GetApiV2PermissionsQueryEntitiesRolesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/entities/roles',
    ...options,
  });

/**
 * Pobranie listy podmiotów podrzędnych
 *
 *  Metoda pozwala na odczytanie listy podmiotów podrzędnych,
 * jeżeli podmiot bieżącego kontekstu ma rolę podmiotu nadrzędnego:
 * - **nadrzędna JST** – odczytywane są podrzędne JST,
 * - **grupa VAT** – odczytywane są podmioty będące członkami grupy VAT.
 *
 * Role podmiotów zwracane przez operację obejmują:
 * - **LocalGovernmentSubUnit** – podrzędne JST,
 * - **VatGroupSubUnit** – członek grupy VAT.
 *
 * Odpowiedź może być filtrowana według parametru:
 * - **subordinateEntityIdentifier** – identyfikator podmiotu podrzędnego.
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy podmiotów podrzędnych](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-podmiot%C3%B3w-podrz%C4%99dnych)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`, `SubunitManage`.
 */
export const postApiV2PermissionsQuerySubordinateEntitiesRoles = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiV2PermissionsQuerySubordinateEntitiesRolesData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsQuerySubordinateEntitiesRolesResponses,
    PostApiV2PermissionsQuerySubordinateEntitiesRolesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/subordinate-entities/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie listy uprawnień podmiotowych do obsługi faktur
 *
 *  Metoda pozwala na odczytanie uprawnień podmiotowych:
 * - otrzymanych przez podmiot bieżącego kontekstu
 * - nadanych przez podmiot bieżącego kontekstu
 *
 * Wybór listy nadanych lub otrzymanych uprawnień odbywa się przy użyciu parametru **queryType**.
 *
 * Uprawnienia zwracane przez operację obejmują:
 * - **SelfInvoicing** – wystawianie faktur w trybie samofakturowania
 * - **TaxRepresentative** – wykonywanie operacji przedstawiciela podatkowego
 * - **RRInvoicing** – wystawianie faktur VAT RR
 * - **PefInvoicing** – wystawianie faktur PEF
 *
 * Odpowiedź może być filtrowana na podstawie następujących parametrów:
 * - **authorizingIdentifier** – identyfikator podmiotu uprawniającego (stosowane przy queryType = Received)
 * - **authorizedIdentifier** – identyfikator podmiotu uprawnionego (stosowane przy queryType = Granted)
 * - **permissionTypes** – lista rodzajów wyszukiwanych uprawnień
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-uprawnie%C5%84-podmiotowych-do-obs%C5%82ugi-faktur)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`, `PefInvoiceWrite`.
 */
export const postApiV2PermissionsQueryAuthorizationsGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsQueryAuthorizationsGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsQueryAuthorizationsGrantsResponses,
    PostApiV2PermissionsQueryAuthorizationsGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/authorizations/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pobranie listy uprawnień administratorów lub reprezentantów podmiotów unijnych uprawnionych do samofakturowania
 *
 *  Metoda pozwala na odczytanie uprawnień administratorów lub reprezentantów podmiotów unijnych:
 * - Jeżeli kontekstem logowania jest NIP, możliwe jest odczytanie uprawnień administratorów podmiotów unijnych powiązanych z podmiotem bieżącego kontekstu, czyli takich, dla których pierwszy człon kontekstu złożonego jest równy NIP-owi kontekstu logowania.
 * - Jeżeli kontekst logowania jest złożony (NIP-VAT UE), możliwe jest pobranie wszystkich uprawnień administratorów i reprezentantów podmiotu w bieżącym kontekście złożonym.
 *
 * Uprawnienia zwracane przez operację obejmują:
 * - **VatUeManage** – zarządzanie uprawnieniami w ramach podmiotu unijnego
 * - **InvoiceWrite** – wystawianie faktur
 * - **InvoiceRead** – przeglądanie faktur
 * - **Introspection** – przeglądanie historii sesji
 *
 * Odpowiedź może być filtrowana na podstawie następujących parametrów:
 * - **vatUeIdentifier** – identyfikator podmiotu unijnego
 * - **authorizedFingerprintIdentifier** – odcisk palca certyfikatu uprawnionej osoby lub podmiotu
 * - **permissionTypes** – lista rodzajów wyszukiwanych uprawnień
 *
 * #### Stronicowanie wyników
 * Zapytanie zwraca **jedną stronę wyników** o numerze i rozmiarze podanym w ścieżce.
 * - Przy pierwszym wywołaniu należy ustawić parametr `pageOffset = 0`.
 * - Jeżeli dostępna jest kolejna strona wyników, w odpowiedzi pojawi się flaga **`hasMore`**.
 * - W takim przypadku można wywołać zapytanie ponownie z kolejnym numerem strony.
 *
 * > Więcej informacji:
 * > - [Pobieranie listy uprawnień](https://github.com/CIRFMF/ksef-docs/blob/main/uprawnienia.md#pobranie-listy-uprawnie%C5%84-administrator%C3%B3w-lub-reprezentant%C3%B3w-podmiot%C3%B3w-unijnych-uprawnionych-do-samofakturowania)
 *
 * **Sortowanie:**
 *
 * - startDate (Desc)
 *
 *
 *
 * **Wymagane uprawnienia**: `CredentialsManage`, `CredentialsRead`, `VatUeManage`.
 */
export const postApiV2PermissionsQueryEuEntitiesGrants = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV2PermissionsQueryEuEntitiesGrantsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV2PermissionsQueryEuEntitiesGrantsResponses,
    PostApiV2PermissionsQueryEuEntitiesGrantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v2/permissions/query/eu-entities/grants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
